Repository MultiEmail/admin, pull requests merged in 2022-12, with the labels that each got.

#83 feat: get all users from API
  .vscode/settings.json
  src/App.tsx
  src/actions/.gitkeep
  src/actions/users.action.ts
  src/components/protected_route/ProtectedRoutes.tsx
  src/pages/login/Login.tsx
  src/pages/users/Users.tsx
  src/reducers/users.reducers.ts
  src/slices/user.slice.ts
  src/store.ts
  src/utils/api.util.ts
Labels: enhancement

#91 feat: api integration to mark user as verified
  package.json
  src/App.tsx
  src/actions/users.action.ts
  src/components/button/Button.tsx
  src/pages/login/Login.tsx
  src/pages/users/Users.tsx
  src/pages/users/user/User.tsx
  src/slices/user.slice.ts
Labels: enhancement

#94 feat: protected route logic
  src/actions/auth.actions.ts
  src/components/protected_route/ProtectedRoutes.tsx
  src/reducers/users.reducers.ts
  src/slices/user.slice.ts
Labels: enhancement, security

#93 feat: API integration to mark user as admin and delete user
  src/actions/users.action.ts
  src/pages/users/user/User.tsx
Labels: enhancement

#96 fix: auto redirect logged in admin to dashboard
  src/App.tsx
  src/pages/login/Login.tsx
Labels: bug

#99 feat: UI for `/users` route
  package-lock.json
  package.json
  src/pages/users/Users.tsx
  yarn.lock
Labels: enhancement
